---
title: Data visualization for life expectancy and other elements of the life table,
  Canada, all provinces except Prince Edward Island dataset
author: "Eva Y"
date: '2018-10-13'
output: 
  html_document: 
    keep_md: yes
editor_options: 
  chunk_output_type: console
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.width=8, fig.height=8,
                      echo=FALSE, warning=FALSE, message=FALSE)

knitr::opts_knit$set(root.dir = "../")
```

```{r load dependency}
library(data.table)
library(ggplot2)
```

```{r load data}
life_data_sep_avg <- fread("results/life_data_sep_avg.csv", sep = ",")
```

## Overview

In this report, I will be visualizing the life expectancy dataset, starting with BC.

## What story can we tell with this dataset? 

How does this worksss? ugh

## British Columbia 

### Number of survivors at age x 

```{r Plot exploratory plot, fig.width=14, fig.height=6}
# change age group data type
life_data_sep_avg[, Age_group := as.integer(Age_group)]

# plot
ggplot(life_data_sep_avg[Element == "Number of survivors at age x (lx)" & GEO == "British Columbia" & Sex %in% c("M", "F") & YEAR %in% seq(1980, 2016, 4)], 
       aes(x = Age_group, y = AVG_VALUE, color = Sex)) +
  geom_point(alpha = 0.6, size = 2) +
  theme_bw() +
  facet_wrap(~ YEAR, ncol = 5) +
  scale_x_continuous(breaks=c(0, seq(20, 120, 20)), limits = c(0, 120)) +
  scale_y_continuous(breaks=c(0, seq(10000, 100000, 10000))) +
  scale_color_discrete(name = "Sex",
                       labels = c("Female", "Male")) +
  theme(legend.title = element_text(size = 16, face = "bold"), 
        legend.text = element_text(size = 16),
        axis.text.y = element_text(size = 14),
        axis.text.x = element_text(size = 12),
        axis.title = element_text(size = 18,face = "bold"), 
        strip.text.x = element_text(size = 18),
        legend.key = element_rect(size = 5),
        legend.key.size = unit(2, 'lines'), 
        plot.title = element_text(size = 22, lineheight=.8, face="bold")) +
  xlab("Age") +
  ylab("Number of survivors") +
  guides(color = guide_legend(override.aes=list(size=5)))
```

### Number of deaths at age x 

```{r Plot exploratory plot 2, fig.width=14, fig.height=6}
# plot
ggplot(life_data_sep_avg[Element == "Number of deaths between age x and x+1 (dx)" & GEO == "British Columbia" & Sex %in% c("M", "F") & YEAR %in% seq(1980, 2016, 4)], 
       aes(x = Age_group, y = AVG_VALUE, color = Sex)) +
  geom_point(alpha = 0.6, size = 2) +
  theme_bw() +
  facet_wrap(~ YEAR, ncol = 5) +
  scale_x_continuous(breaks=c(0, seq(20, 120, 20)), limits = c(0, 120)) +
  scale_y_continuous(breaks=seq(0, 5000, 500)) +
  scale_color_discrete(name = "Sex",
                       labels = c("Female", "Male")) +
  theme(legend.title = element_text(size = 16, face = "bold"), 
        legend.text = element_text(size = 16),
        axis.text.y = element_text(size = 14),
        axis.text.x = element_text(size = 12),
        axis.title = element_text(size = 18,face = "bold"), 
        strip.text.x = element_text(size = 18),
        legend.key = element_rect(size = 5),
        legend.key.size = unit(2, 'lines'), 
        plot.title = element_text(size = 22, lineheight=.8, face="bold")) +
  xlab("Age") +
  ylab("Number of deaths") +
  guides(color = guide_legend(override.aes=list(size=5)))
```
